### ISSUE TITLE
spec_to_rgb

### ISSUE THREAD

**Issue by Yecoder** [LoveDaisy/optical_system_simulation#2]
Thank you for your work, but what is the purpose of the function **spec_to_rgb()**? I also did not find an implementation of this function.

**Comment by LoveDaisy** [comment]
Oh that's a function generating RGB colors from spectrums. I didn't describe it in detail. Actually it is in another project, and you can refer to [this project](https://github.com/LoveDaisy/spec_render)

**Comment by LoveDaisy** [comment]
I have updated my codes and repository. Now this function has been moved to [Color Science Util](https://github.com/LoveDaisy/ColorScienceUtils). And I also add a notification about it in README.
